# Generated by Django 6.0.2 on 2026-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_position',
            field=models.IntegerField(default=50),
        ),
    ]
