# Generated by Django 6.0.2 on 2026-04-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='post_images/MemeFactory_default_profileimg.png', upload_to='post_images'),
        ),
    ]
