# Generated by Django 6.0.2 on 2026-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='MemeFactory_default_profileimg.png', upload_to=''),
        ),
    ]
