# Generated by Django 6.0.2 on 2026-04-24 19:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_image_alter_profile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='default_banner', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='default_dp', max_length=255, verbose_name='image'),
        ),
    ]
