# Generated by Django 6.0.2 on 2026-04-24 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_banner_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=cloudinary.models.CloudinaryField(default='default_banner_qqfqri', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='MemeFactory_default_profileimg_okvgn4', max_length=255, verbose_name='image'),
        ),
    ]
