# Generated by Django 6.0.2 on 2026-04-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_position',
            field=models.IntegerField(default=30),
        ),
    ]
